### ISSUE TITLE
Create draft PEP

### ISSUE THREAD

**Issue by pombredanne** [pombredanne/spdx-pypi-pep#1]
The goal is to add support for SPDX licenses ID in Pypi packages.
Based on a discussion started by @devcurmudgeon and @jaraco in https://github.com/jaraco/keyring/issues/263

@goneall @sschuberth  @hugo-bmwcarit you may be interested by this too
If so tell it here and I will add you to the repo.

**Comment by pombredanne** [comment]
@kpfleming @taleinat  I gave you both push access to this repo.
And I started a draft PEP at https://github.com/python/peps/pull/1148

**Comment by pombredanne** [comment]
@tieguy ping too :)

**Comment by pombredanne** [comment]
And also https://discuss.python.org/t/improving-license-clarity-with-better-package-metadata/2154

**Comment by pombredanne** [comment]
@kpfleming @taleinat this is the draft PEP file https://github.com/pombredanne/spdx-pypi-pep/blob/metadata-2.2-spdx-license/pep-9999.rst ... You can edit directly in that branch (metadata-2.2-spdx-license) to update the draft (and the PR). For a start you can add yourself as co-authors there. 
@Steap do you want to join to co-author this PEP?

Note: @pfmoore kindly offered to be both the BDFL delegate and the sponsor for this PEP :bowing_man:

**Comment by Steap** [comment]
@pombredanne I would love to join!

Shouldn't we keep the discussion going at https://discuss.python.org/t/improving-license-clarity-with-better-package-metadata/2154/15 for now?

**Comment by pombredanne** [comment]
@Steap I am giving you push access to this repo

> Shouldn't we keep the discussion going at https://discuss.python.org/t/improving-license-clarity-with-better-package-metadata/2154/15 for now?

The process should be IMHO:
1. the discussion is on https://discuss.python.org/t/improving-license-clarity-with-better-package-metadata/2154/15 
2. the results of the discussion end up in the PEP and PR (and the end results may not be a PEP in the end, but having a proper consolidated document with all in one place is better IMHO)

**Comment by pombredanne** [comment]
I am closing this as we have the PR and the discuss paces for feedback and review
