### ISSUE TITLE
Mention or propose migration strategy?

### ISSUE THREAD

**Issue by tieguy** [pombredanne/spdx-pypi-pep#4]
I don’t know what Python’s norms for PEPs are, but certainly if I were a Python dev seeing this I’d be more comfortable if a migration strategy was at least suggested for the deprecated fields. But perhaps that is handled in a different part of the process?

**Comment by pombredanne** [comment]
@tieguy excellent point!

this has been addressed in the latest draft that you see in https://github.com/pombredanne/spdx-pypi-pep/pull/2/files

There is no deprecation anymore

Feel free to comment directly on the PR btw
Thank you!
