### ISSUE TITLE
Possible helpful example - pillow license

### ISSUE THREAD

**Issue by tieguy** [pombredanne/spdx-pypi-pep#5]
Real world example of this popping up, possibly useful but maybe overkill: https://github.com/python-pillow/Pillow/issues/1507

**Comment by pombredanne** [comment]
@tieguy this is an interesting example on multiple counts.
-  this was something that I tracked in ScanCode as the cmu-uc license https://github.com/nexB/scancode-toolkit/blob/f76b3b9adf529d7db0e1e3053c2768351d3a92ab/src/licensedcode/data/licenses/cmu-uc.LICENSE 
- this has now recently been added at SPDX as the MIT-CMU https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/cmu-uc.yml
- See https://github.com/spdx/license-list-XML/issues/907 so this is not an HPND (though is close enough)

**Comment by pombredanne** [comment]
Just as a side note: relying on the GH api (e.g. licensee) or Libraries.io (e.g. package manifests) for license detection is kinda rather limited.

**Comment by tieguy** [comment]
Agreed re CMU, I've since switched to a more automated detection system
(that was done with my eyeballs, which are flawed!) Going to apologize to
Pillow and get it fixed, but wanted pypa to get to a better place first.

Definitely agreed re the limitations of those two APIs, but our approach
has been that this is a good starting point because it provides a
manageable starting point for most developers and identifies many of the
most egregious problems. More complete/accurate approaches are often a
developer experience nightmare requiring much analysis, coaching,
explanation, etc. But would be happy to discuss in discord when I'm back
from my next round of travels.

**Comment by pombredanne** [comment]
@tieguy in anycase this is a good example of something that will benefit of using SPDX license expressions and could not be captured with Classifiers today. I am closing this now as we are closing on an official draft PEP
